services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arpi-isms-php
    volumes:
      - .:/var/www/html/arpi-isms
    working_dir: /var/www/html/arpi-isms
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DATABASE=arpi
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    secrets:
      - mongodb_username
      - mongodb_password
      - redis_password
    networks:
      - arpi-network

  mongo:
    image: mongo:8.0.15
    container_name: arpi-isms-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongodb_username
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongodb_password
    secrets:
      - mongodb_username
      - mongodb_password
    command: ["mongod", "--replSet", "rs0"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - arpi-network

secrets:
  mongodb_username:
    file: ./secrets/mongodb_username.txt
  mongodb_password:
    file: ./secrets/mongodb_password.txt
  redis_password:
    file: ./secrets/redis_password.txt

volumes:
  mongo-data:

networks:
  arpi-network:
    driver: bridge
